/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
 */
        CKEDITOR.plugins.setLang("specialchar", "cs", {euro:"Znak eura", lsquo:"Po�?áte�?ní uvozovka jednoduchá", rsquo:"Koncová uvozovka jednoduchá", ldquo:"Po�?áte�?ní uvozovka dvojitá", rdquo:"Koncová uvozovka dvojitá", ndash:"En poml�?ka", mdash:"Em poml�?ka", iexcl:"Obrácený vykři�?ník", cent:"Znak centu", pound:"Znak libry", curren:"Znak měny", yen:"Znak jenu", brvbar:"Přerušená svislá �?ára", sect:"Znak oddílu", uml:"Přehláska", copy:"Znak copyrightu", ordf:"Ženský indikátor rodu", laquo:"Znak dvojitých lomených uvozovek vlevo",
                not:"Logistický zápor", reg:"Znak registrace", macr:"Poml�?ka nad", deg:"Znak stupně", sup2:"Dvojka jako horní index", sup3:"Trojka jako horní index", acute:"Čárka nad vpravo", micro:"Znak mikro", para:"Znak odstavce", middot:"Te�?ka uprostřed", cedil:"Ocásek vlevo", sup1:"Jedni�?ka jako horní index", ordm:"Mužský indikátor rodu", raquo:"Znak dvojitých lomených uvozovek vpravo", frac14:"Oby�?ejný zlomek jedna �?tvrtina", frac12:"Oby�?ejný zlomek jedna polovina", frac34:"Oby�?ejný zlomek tři �?tvrtiny", iquest:"Znak obráceného otazníku",
                Agrave:"Velké písmeno latinky A s �?árkou nad vlevo", Aacute:"Velké písmeno latinky A s �?árkou nad vpravo", Acirc:"Velké písmeno latinky A s vokáněm", Atilde:"Velké písmeno latinky A s tildou", Auml:"Velké písmeno latinky A s dvěma te�?kami", Aring:"Velké písmeno latinky A s kroužkem nad", AElig:"Velké písmeno latinky Æ", Ccedil:"Velké písmeno latinky C s ocáskem vlevo", Egrave:"Velké písmeno latinky E s �?árkou nad vlevo", Eacute:"Velké písmeno latinky E s �?árkou nad vpravo", Ecirc:"Velké písmeno latinky E s vokáněm",
                Euml:"Velké písmeno latinky E s dvěma te�?kami", Igrave:"Velké písmeno latinky I s �?árkou nad vlevo", Iacute:"Velké písmeno latinky I s �?árkou nad vpravo", Icirc:"Velké písmeno latinky I s vokáněm", Iuml:"Velké písmeno latinky I s dvěma te�?kami", ETH:"Velké písmeno latinky Eth", Ntilde:"Velké písmeno latinky N s tildou", Ograve:"Velké písmeno latinky O s �?árkou nad vlevo", Oacute:"Velké písmeno latinky O s �?árkou nad vpravo", Ocirc:"Velké písmeno latinky O s vokáněm", Otilde:"Velké písmeno latinky O s tildou",
                Ouml:"Velké písmeno latinky O s dvěma te�?kami", times:"Znak násobení", Oslash:"Velké písmeno latinky O přeškrtnuté", Ugrave:"Velké písmeno latinky U s �?árkou nad vlevo", Uacute:"Velké písmeno latinky U s �?árkou nad vpravo", Ucirc:"Velké písmeno latinky U s vokáněm", Uuml:"Velké písmeno latinky U s dvěma te�?kami", Yacute:"Velké písmeno latinky Y s �?árkou nad vpravo", THORN:"Velké písmeno latinky Thorn", szlig:"Malé písmeno latinky ostré s", agrave:"Malé písmeno latinky a s �?árkou nad vlevo", aacute:"Malé písmeno latinky a s �?árkou nad vpravo",
                acirc:"Malé písmeno latinky a s vokáněm", atilde:"Malé písmeno latinky a s tildou", auml:"Malé písmeno latinky a s dvěma te�?kami", aring:"Malé písmeno latinky a s kroužkem nad", aelig:"Malé písmeno latinky ae", ccedil:"Malé písmeno latinky c s ocáskem vlevo", egrave:"Malé písmeno latinky e s �?árkou nad vlevo", eacute:"Malé písmeno latinky e s �?árkou nad vpravo", ecirc:"Malé písmeno latinky e s vokáněm", euml:"Malé písmeno latinky e s dvěma te�?kami", igrave:"Malé písmeno latinky i s �?árkou nad vlevo", iacute:"Malé písmeno latinky i s �?árkou nad vpravo",
                icirc:"Malé písmeno latinky i s vokáněm", iuml:"Malé písmeno latinky i s dvěma te�?kami", eth:"Malé písmeno latinky eth", ntilde:"Malé písmeno latinky n s tildou", ograve:"Malé písmeno latinky o s �?árkou nad vlevo", oacute:"Malé písmeno latinky o s �?árkou nad vpravo", ocirc:"Malé písmeno latinky o s vokáněm", otilde:"Malé písmeno latinky o s tildou", ouml:"Malé písmeno latinky o s dvěma te�?kami", divide:"Znak dělení", oslash:"Malé písmeno latinky o přeškrtnuté", ugrave:"Malé písmeno latinky u s �?árkou nad vlevo",
                uacute:"Malé písmeno latinky u s �?árkou nad vpravo", ucirc:"Malé písmeno latinky u s vokáněm", uuml:"Malé písmeno latinky u s dvěma te�?kami", yacute:"Malé písmeno latinky y s �?árkou nad vpravo", thorn:"Malé písmeno latinky thorn", yuml:"Malé písmeno latinky y s dvěma te�?kami", OElig:"Velká ligatura latinky OE", oelig:"Malá ligatura latinky OE", 372:"Velké písmeno latinky W s vokáněm", 374:"Velké písmeno latinky Y s vokáněm", 373:"Malé písmeno latinky w s vokáněm", 375:"Malé písmeno latinky y s vokáněm", sbquo:"Dolní 9 uvozovka jednoduchá",
                8219:"Horní obrácená 9 uvozovka jednoduchá", bdquo:"Dolní 9 uvozovka dvojitá", hellip:"Trojte�?kový úvod", trade:"Obchodní zna�?ka", 9658:"Černý ukazatel směřující vpravo", bull:"Kole�?ko", rarr:"Šipka vpravo", rArr:"Dvojitá šipka vpravo", hArr:"Dvojitá šipka vlevo a vpravo", diams:"Černé piky", asymp:"Téměř se rovná"});