/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
 */
        CKEDITOR.plugins.setLang("specialchar", "ko", {euro:"유로화 기호", lsquo:"왼쪽 외 따옴표", rsquo:"오른쪽 외 따옴표", ldquo:"왼쪽 �? 따옴표", rdquo:"오른쪽 �? 따옴표", ndash:"반�? 대시", mdash:"전�? 대시", iexcl:"반전�?� �?낌표", cent:"센트 기호", pound:"파운드화 기호", curren:"커런시 기호", yen:"위안화 기호", brvbar:"파선", sect:"섹션 기호", uml:"분�?� 부호", copy:"저작권 기호", ordf:"Feminine ordinal indicator", laquo:"왼쪽 �?꺽쇠 �?�용 부호", not:"금지 기호", reg:"등�? 기호", macr:"장�?� 기호", deg:"�?� 기호", sup2:"위첨�? 2", sup3:"위첨�? 3", acute:"양�?� 악센트 부호", micro:"마�?��?�로 기호", para:"단�?� 기호", middot:"가운�?� �?", cedil:"세디유", sup1:"위첨�? 1", ordm:"Masculine ordinal indicator",
                raquo:"오른쪽 �?꺽쇠 �?�용 부호", frac14:"분수 사분�?� �?�", frac12:"분수 �?�분�?� �?�", frac34:"분수 사분�?� 삼", iquest:"뒤집힌 물�?�표", Agrave:"억�?� 부호가 있는 �?�틴 대문�? A", Aacute:"양�?� 악센트 부호가 있는 �?�틴 대문�? A", Acirc:"곡절 악센트 부호가 있는 �?�틴 대문�? A", Atilde:"틸�?�가 있는 �?�틴 대문�? A", Auml:"분�?� 기호가 있는 �?�틴 대문�? A", Aring:"윗고리가 있는 �?�틴 대문�? A", AElig:"�?�틴 대문�? Æ", Ccedil:"세디유가 있는 �?�틴 대문�? C", Egrave:"억�?� 부호가 있는 �?�틴 대문�? E", Eacute:"양�?� 악센트 부호가 있는 �?�틴 대문�? E", Ecirc:"곡절 악센트 부호가 있는 �?�틴 대문�? E", Euml:"분�?� 기호가 있는 �?�틴 대문�? E", Igrave:"억�?� 부호가 있는 �?�틴 대문�? I", Iacute:"양�?� 악센트 부호가 있는 �?�틴 대문�? I", Icirc:"곡절 악센트 부호가 있는 �?�틴 대문�? I",
                Iuml:"분�?� 기호가 있는 �?�틴 대문�? I", ETH:"�?�틴 대문�? Eth", Ntilde:"틸�?�가 있는 �?�틴 대문�? N", Ograve:"억�?� 부호가 있는 �?�틴 대문�? O", Oacute:"양�?� 부호가 있는 �?�틴 대문�? O", Ocirc:"곡절 악센트 부호가 있는 �?�틴 대문�? O", Otilde:"틸�?�가 있는 �?�틴 대문�? O", Ouml:"분�?� 기호가 있는 �?�틴 대문�? O", times:"곱하기 기호", Oslash:"사선�?� 있는 �?�틴 대문�? O", Ugrave:"억�?� 부호가 있는 �?�틴 대문�? U", Uacute:"양�?� 부호가 있는 �?�틴 대문�? U", Ucirc:"곡절 악센트 부호가 있는 �?�틴 대문�? U", Uuml:"분�?� 기호가 있는 �?�틴 대문�? U", Yacute:"양�?� 부호가 있는 �?�틴 대문�? Y", THORN:"�?�틴 대문�? Thorn", szlig:"�?�틴 소문�? sharp s", agrave:"억�?� 부호가 있는 �?�틴 소문�? a", aacute:"양�?� 부호가 있는 �?�틴 소문�? a", acirc:"곡절 악센트 부호가 있는 �?�틴 소문�? a",
                atilde:"틸�?�가 있는 �?�틴 소문�? a", auml:"분�?� 기호가 있는 �?�틴 소문�? a", aring:"윗고리가 있는 �?�틴 소문�? a", aelig:"�?�틴 소문�? æ", ccedil:"세디유가 있는 �?�틴 소문�? c", egrave:"억�?� 부호가 있는 �?�틴 소문�? e", eacute:"양�?� 부호가 있는 �?�틴 소문�? e", ecirc:"곡절 악센트 부호가 있는 �?�틴 소문�? e", euml:"분�?� 기호가 있는 �?�틴 소문�? e", igrave:"억�?� 부호가 있는 �?�틴 소문�? i", iacute:"양�?� 부호가 있는 �?�틴 소문�? i", icirc:"곡절 악센트 부호가 있는 �?�틴 소문�? i", iuml:"분�?� 기호가 있는 �?�틴 소문�? i", eth:"�?�틴 소문�? eth", ntilde:"틸�?�가 있는 �?�틴 소문�? n", ograve:"억�?� 부호가 있는 �?�틴 소문�? o", oacute:"양�?� 부호가 있는 �?�틴 소문�? o", ocirc:"곡절 악센트 부호가 있는 �?�틴 소문�? o", otilde:"틸�?�가 있는 �?�틴 소문�? o", ouml:"분�?� 기호가 있는 �?�틴 소문�? o",
                divide:"나누기 기호", oslash:"사선�?� 있는 �?�틴 소문�? o", ugrave:"억�?� 부호가 있는 �?�틴 소문�? u", uacute:"양�?� 부호가 있는 �?�틴 소문�? u", ucirc:"곡절 악센트 부호가 있는 �?�틴 소문�? u", uuml:"분�?� 기호가 있는 �?�틴 소문�? u", yacute:"양�?� 부호가 있는 �?�틴 소문�? y", thorn:"�?�틴 소문�? thorn", yuml:"분�?� 기호가 있는 �?�틴 소문�? y", OElig:"�?�틴 대문합�? OE", oelig:"�?�틴 소문합�? oe", 372:"곡절 악센트 부호가 있는 �?�틴 대문�? W", 374:"곡절 악센트 부호가 있는 �?�틴 대문�? Y", 373:"곡절 악센트 부호가 있는 �?�틴 소문�? w", 375:"곡절 악센트 부호가 있는 �?�틴 소문�? y", sbquo:"외 아래-9 �?�용 부호", 8219:"외 위쪽-뒤집힌-9 �?�용 부호", bdquo:"�? 아래-9 �?�용 부호", hellip:"수�?� �?략 부호", trade:"�?표 기호", 9658:"검정 오른쪽 �?��?�터", bull:"�?� �?",
                rarr:"오른쪽 화살표", rArr:"오른쪽 �? 줄 화살표", hArr:"양쪽 �? 줄 화살표", diams:"검정 다�?�아몬드", asymp:"근사"});