/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
 */
        CKEDITOR.plugins.setLang("specialchar", "sr-latn", {euro:"Znak eura", lsquo:"Levi simpli znak navoda", rsquo:"Desni simpli znak navoda", ldquo:"Levi dupli znak navoda", rdquo:"Desni dupli znak navoda", ndash:"Kratka crtica", mdash:"DugaÄ?ka crtica", iexcl:"Obrnuti uzviÄ?nik", cent:"Znak za cent", pound:"Znak za funtĞµ", curren:"Znak za valutu", yen:"Znak za jenĞ°", brvbar:"Traka sa prekidom", sect:"Znak paragrafa", uml:"Umlaut", copy:"Znak za autorsko pravo", ordf:"Å½enski redni indikator", laquo:"Dupla strelica levo", not:"Bez znaka",
                reg:"Registrovani znak", macr:"Znak duÅ¾ine", deg:"Znak za stepen", sup2:"Znak za kvadrat", sup3:"Znak za kub", acute:"OÅ¡tar akcenat", micro:"Znak mikro", para:"Znak pasusa", middot:"Srednja taÄ?ka", cedil:"Cedila", sup1:"Znak na prvom", ordm:"MuÅ¡ki redni indikator", raquo:"Dupla strelica desno", frac14:"Znak za Ä?etvrtinu", frac12:"Znak za polovinu", frac34:"Znak za treÄ‡inu", iquest:"Obrnuti upitnik", Agrave:"Veliko latiniÄ?no slovo A sa  obrnutom kukicom.", Aacute:"Veliko latiniÄ?no slovo A sa kukicom.", Acirc:"Veliko latiniÄ?no slovo A sa savijenom kukicom.",
                Atilde:"Veliko latiniÄ?no slovo A sa znakom talasa.", Auml:"Veliko latiniÄ?no slovo A sa dvotaÄ?kom", Aring:"Veliko latiniÄ?no slovo A sa prstenom iznad.", AElig:"Veliko latiniÄ?no slovo Ã†", Ccedil:"Veliko latiniÄ?no slovo C sa cedilom", Egrave:"Veliko latiniÄ?no slovo E sa obrnutom kukicom", Eacute:"Veliko latiniÄ?no slovo E sa kukicom.", Ecirc:"Veliko latiniÄ?no slovo E sa savijenom kukicom.", Euml:"Veliko latiniÄ?no slovo E sa dvotaÄ?kom", Igrave:"Veliko latiniÄ?no slovo I sa obrnutom kukicom", Iacute:"Veliko latiniÄ?no slovo I sa kukicom.",
                Icirc:"Veliko latiniÄ?no slovo I sa savijenom kukicom.", Iuml:"Veliko latiniÄ?no slovo I sa dvotaÄ?kom", ETH:"Veliko latiniÄ?no slovo Eth", Ntilde:"Veliko latiniÄ?no slovo N sa znakom talasa.", Ograve:"Veliko latiniÄ?no slovo O sa obrnutom kukicom", Oacute:"Veliko latiniÄ?no slovo O sa kukicom.", Ocirc:"Veliko latiniÄ?no slovo O sa savijenom kukicom.", Otilde:"Veliko latiniÄ?no slovo O sa znakom talasa.", Ouml:"Veliko latiniÄ?no slovo O sa dvotaÄ?kom", times:"Znak mnoÅ¾enja", Oslash:"LatiniÄ?no slovo O precrtano", Ugrave:"Veliko latiniÄ?no slovo U sa obrnutom kukicom",
                Uacute:"Veliko latiniÄ?no slovo U sa kukicom", Ucirc:"Veliko latiniÄ?no slovo U sa savijenom kukicom.", Uuml:"Veliko latiniÄ?no slovo U sa dvotaÄ?kom", Yacute:"Veliko latiniÄ?no slovo Y sa kukicom", THORN:"Veliko latiniÄ?no slovo Thotn", szlig:"Malo latiniÄ?no slovo s", agrave:"Malo latiniÄ?no slovo a sa obrnutom kukicom", aacute:"Malo latiniÄ?no slovo a sa kukicom", acirc:"Malo latiniÄ?no slovo a sa savijenom kukicom", atilde:"Malo latiniÄ?no slovo a sa znakom talasa", auml:"Malo latiniÄ?no slovo a sa dvotaÄ?kom", aring:"Malo latiniÄ?no slovo a sa prstenom iznad",
                aelig:"Malo latiniÄ?no slovo Ã¦", ccedil:"Malo latiniÄ?no slovo c sa cedilom", egrave:"Malo latiniÄ?no slovo e sa obrnutom kukicom", eacute:"Malo latiniÄ?no slovo e sa kukicom", ecirc:"Malo latiniÄ?no slovo e sa savijenom kukicom", euml:"Malo latiniÄ?no slovo e sa dvotaÄ?kom", igrave:"Malo latiniÄ?no slovo i sa obrnutom kukicom", iacute:"Malo latiniÄ?no slovo i sa kukicom", icirc:"Malo latiniÄ?no slovo i sa savijenom kukicom", iuml:"Malo latiniÄ?no slovo i sa dvotaÄ?kom", eth:"Malo latiniÄ?no slovo eth", ntilde:"Malo latiniÄ?no slovo n sa znakom talasa",
                ograve:"Malo latiniÄ?no slovo o sa obrnutom kukicom", oacute:"Malo latiniÄ?no slovo o sa kukicom", ocirc:"Malo latiniÄ?no slovo o sa savijenom kukicom", otilde:"Malo latiniÄ?no slovo o sa znakom talasa", ouml:"Malo latiniÄ?no slovo o dvotaÄ?kom", divide:"Znak deljenja", oslash:"Malo latiniÄ?no slovo o precrtano", ugrave:"Malo latiniÄ?no slovo u sa obrnutom kukicom", uacute:"Malo latiniÄ?no slovo u sa kukicom", ucirc:"Malo latiniÄ?no slovo u sa savijenom kukicom", uuml:"Malo latiniÄ?no slovo u sa dvotaÄ?kom", yacute:"Malo latiniÄ?no slovo y sa kukicom",
                thorn:"Malo latiniÄ?no slovo thorn", yuml:"Malo latiniÄ?no slovo y sa dvotaÄ?kom", OElig:"Veliki latiniÄ?ni znak OE", oelig:"Mali latiniÄ?ni znak OE", 372:"Veliko latiniÄ?no slovo W sa savijenom kukicom.", 374:"Veliko latiniÄ?no slovo Y sa savijenom kukicom.", 373:"Malo latiniÄ?no slovo w sa savijenom kukicom.", 375:"Malo latiniÄ?no slovo y sa savijenom kukicom.", sbquo:"Tipografski simpli navodnik za otvaranje", 8219:"Tipografski simpli navodnik za zatvaranje", bdquo:"Tipografski dupli navodnik ", hellip:"Tri taÄ?ke",
                trade:"Znak robne marke", 9658:"Crni pokazivaÄ? desno", bull:"TaÄ?ka", rarr:"Strelica desno", rArr:"Dupla strelica desno", hArr:"Levo desno dupla strelica", diams:"Crni dijamant znak", asymp:"Znak skoro jednako"});