/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
 */
        CKEDITOR.plugins.setLang("a11yhelp", "he", {title:"הור�?ות נגישות", contents:"הור�?ות נגישות. לסגירה לחץ �?סקייפ (ESC).", legend:[{name:"כללי", items:[{name:"סרגל הכלי�?", legend:"לחץ על ${toolbarFocus} כדי לנווט לסרגל הכלי�?. עבור לכפתור הב�? ע�? מקש הט�?ב (TAB) �?ו חץ שמ�?לי. עבור לכפתור הקוד�? ע�? מקש השיפט (SHIFT) + ט�?ב (TAB) �?ו חץ ימני. לחץ רווח �?ו �?נטר (ENTER) כדי להפעיל �?ת הכפתור הנבחר."}, {name:"די�?לוגי�? (חלונות תש�?ול)", legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},
        {name:"תפריט ההקשר (Context Menu)", legend:"לחץ ${contextMenu} �?ו APPLICATION KEYכדי לפתוח �?ת תפריט ההקשר. עבור ל�?פשרות הב�?ה ע�? ט�?ב (TAB) �?ו חץ למטה. עבור ל�?פשרות הקודמת ע�? שיפט (SHIFT) + ט�?ב (TAB) �?ו חץ למעלה. לחץ רווח �?ו �?נטר (ENTER) כדי לבחור �?ת ה�?פשרות. פתח �?ת תת התפריט (Sub-menu) של ה�?פשרות הנוכחית ע�? רווח �?ו �?נטר (ENTER) �?ו חץ שמ�?לי. חזור לתפריט ה�?ב ע�? �?סקייפ (ESC) �?ו חץ שמ�?לי. סגור �?ת תפריט ההקשר ע�? �?סקייפ (ESC)."}, {name:"תפריטי�? צפי�? (List boxes)", legend:"Inside a list-box, move to next list item with TAB OR DOWN ARROW. Move to previous list item with SHIFT+TAB or UP ARROW. Press SPACE or ENTER to select the list option. Press ESC to close the list-box."},
        {name:"עץ �?למנטי�? (Elements Path)", legend:"לחץ ${elementsPathFocus} כדי לנווט לעץ ה�?למנטי�?. עבור לפריט הב�? ע�? ט�?ב (TAB) �?ו חץ ימני. עבור לפריט הקוד�? ע�? שיפט (SHIFT) + ט�?ב (TAB) �?ו חץ שמ�?לי. לחץ רווח �?ו �?נטר (ENTER) כדי לבחור �?ת ה�?למנט בעורך."}]}, {name:"פקודות", items:[{name:" ביטול צעד �?חרון", legend:"לחץ ${undo}"}, {name:" חזרה על צעד �?חרון", legend:"לחץ ${redo}"}, {name:" הדגשה", legend:"לחץ ${bold}"}, {name:" הטייה", legend:"לחץ ${italic}"}, {name:" הוספת קו תחתון", legend:"לחץ ${underline}"}, {name:" הוספת לינק",
                legend:"לחץ ${link}"}, {name:" כיווץ סרגל הכלי�?", legend:"לחץ ${toolbarCollapse}"}, {name:"גישה למיקו�? המיקוד הקוד�?", legend:"לחץ ${accessPreviousSpace} כדי לגשת למיקו�? המיקוד הל�?-נגיש הקרוב לפני הסמן, למשל בין שני �?למנטי�? סמוכי�? מסוג HR. חזור על צירוף מקשי�? זה כדי להגיע למקומות מיקוד רחוקי�? יותר."}, {name:"גישה למיקו�? המיקוד הב�?", legend:"לחץ ${accessNextSpace} כדי לגשת למיקו�? המיקוד הל�?-נגיש הקרוב �?חרי הסמן, למשל בין שני �?למנטי�? סמוכי�? מסוג HR. חזור על צירוף מקשי�? זה כדי להגיע למקומות מיקוד רחוקי�? יותר."},
        {name:" הור�?ות נגישות", legend:"לחץ ${a11yHelp}"}, {name:" Paste as plain text", legend:"Press ${pastetext}", legendEdge:"Press ${pastetext}, followed by ${paste}"}]}], tab:"Tab", pause:"Pause", capslock:"Caps Lock", escape:"Escape", pageUp:"Page Up", pageDown:"Page Down", leftArrow:"חץ שמ�?לה", upArrow:"חץ למעלה", rightArrow:"חץ ימינה", downArrow:"חץ למטה", insert:"הכנס", leftWindowKey:"Left Windows key", rightWindowKey:"Right Windows key", selectKey:"בחר מקש", numpad0:"Numpad 0", numpad1:"Numpad 1", numpad2:"Numpad 2",
                numpad3:"Numpad 3", numpad4:"Numpad 4", numpad5:"Numpad 5", numpad6:"Numpad 6", numpad7:"Numpad 7", numpad8:"Numpad 8", numpad9:"Numpad 9", multiply:"Multiply", add:"הוסף", subtract:"Subtract", decimalPoint:"Decimal Point", divide:"Divide", f1:"F1", f2:"F2", f3:"F3", f4:"F4", f5:"F5", f6:"F6", f7:"F7", f8:"F8", f9:"F9", f10:"F10", f11:"F11", f12:"F12", numLock:"Num Lock", scrollLock:"Scroll Lock", semiColon:"Semicolon", equalSign:"Equal Sign", comma:"Comma", dash:"Dash", period:"Period", forwardSlash:"סל�?ש", graveAccent:"Grave Accent",
                openBracket:"Open Bracket", backSlash:"סל�?ש הפוך", closeBracket:"Close Bracket", singleQuote:"ציטוט יחיד"});