/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
 */
        CKEDITOR.plugins.setLang("a11yhelp", "sk", {title:"Inštrukcie prístupnosti", contents:"Pomocný obsah. Pre zatvorenie tohto okna, stla�?te ESC.", legend:[{name:"Všeobecne", items:[{name:"Lišta nástrojov editora", legend:"Stla�?te ${toolbarFocus} pre navigáciu na lištu nástrojov. Medzi �?alšou a predchádzajúcou lištou nástrojov sa pohybujete s TAB a SHIFT+TAB. Medzi �?alším a predchádzajúcim tla�?idlom na lište nástrojov sa pohybujete s pravou šípkou a ľavou šípkou. Stla�?te medzerník alebo ENTER pre aktiváciu tla�?idla lišty nástrojov."},
        {name:"Editorový dialóg", legend:"V dialógovom okne stla�?te TAB pre presun na �?alší prvok, SHIFT+TAB pre presun na predchádzajúci prvok, ENTER pre odoslanie, ESC pre zrušenie. Ke�? má dialógové okno viacero kariet, zoznam kariet dosiahnete bu�? stla�?ením ALT+F10 alebo s TAB v príslušnom poradí kariet. So zameraným zoznamom kariet sa pohybujte k �?alšej alebo predchádzajúcej karte cez PRAVÚ a ĽAVÚ Š�?PKU."}, {name:"Editorové kontextové menu", legend:"Stla�?te ${contextMenu} alebo APPLICATION KEY pre otvorenie kontextového menu. Potom sa presúvajte na �?alšie možnosti menu s TAB alebo dolnou šípkou. Presunte sa k predchádzajúcej možnosti s SHIFT+TAB alebo hornou šípkou. Stla�?te medzerník alebo ENTER pre výber možnosti menu. Otvorte pod-menu danej možnosti s medzerníkom, alebo ENTER, alebo pravou šípkou. Vráťte sa späť do položky rodi�?ovského menu s ESC alebo ľavou šípkou. Zatvorte kontextové menu s ESC."},
        {name:"Editorov box zoznamu", legend:"V boxe zoznamu, presuňte sa na �?alšiu položku v zozname s TAB alebo dolnou šípkou. Presuňte sa k predchádzajúcej položke v zozname so SHIFT+TAB alebo hornou šípkou. Stla�?te medzerník alebo ENTER pre výber možnosti zoznamu. Stla�?te ESC pre zatvorenie boxu zoznamu."}, {name:"Editorove pásmo cesty prvku", legend:"Stla�?te ${elementsPathFocus} pre navigovanie na pásmo cesty elementu. Presuňte sa na tla�?idlo �?alšieho prvku s TAB alebo pravou šípkou. Presuňte sa k predchádzajúcemu tla�?idlu s SHIFT+TAB alebo ľavou šípkou. Stla�?te medzerník alebo ENTER pre výber prvku v editore."}]},
        {name:"Príkazy", items:[{name:"Vrátiť príkazy", legend:"Stla�?te ${undo}"}, {name:"Nanovo vrátiť príkaz", legend:"Stla�?te ${redo}"}, {name:"Príkaz na stu�?nenie", legend:"Stla�?te ${bold}"}, {name:"Príkaz na kurzívu", legend:"Stla�?te ${italic}"}, {name:"Príkaz na pod�?iarknutie", legend:"Stla�?te ${underline}"}, {name:"Príkaz na odkaz", legend:"Stla�?te ${link}"}, {name:"Príkaz na zbalenie lišty nástrojov", legend:"Stla�?te ${toolbarCollapse}"}, {name:"Prejsť na predchádzajúcu zamerateľnú medzeru príkazu", legend:"Stla�?te ${accessPreviousSpace} pre prístup na najbližšie nedosiahnuteľné zamerateľné medzery pred vsuvkuo. Napríklad: dve za sebou idúce horizontálne �?iary. Opakujte kombináciu klávesov pre dosiahnutie vzdialených zamerateľných medzier."},
        {name:"Prejsť na �?alší ", legend:"Stla�?te ${accessNextSpace} pre prístup na najbližšie nedosiahnuteľné zamerateľné medzery po vsuvke. Napríklad: dve za sebou idúce horizontálne �?iary. Opakujte kombináciu klávesov pre dosiahnutie vzdialených zamerateľných medzier."}, {name:"Pomoc prístupnosti", legend:"Stla�?te ${a11yHelp}"}, {name:"Vložiť ako �?istý text", legend:"Stla�?te ${pastetext}", legendEdge:"Stla�?te ${pastetext} a potom ${paste}"}]}], tab:"Tab", pause:"Pause", capslock:"Caps Lock", escape:"Escape", pageUp:"Stránka hore",
                pageDown:"Stránka dole", leftArrow:"Šípka naľavo", upArrow:"Šípka hore", rightArrow:"Šípka napravo", downArrow:"Šípka dole", insert:"Insert", leftWindowKey:"Ľavé Windows tla�?idlo", rightWindowKey:"Pravé Windows tla�?idlo", selectKey:"Tla�?idlo Select", numpad0:"Numpad 0", numpad1:"Numpad 1", numpad2:"Numpad 2", numpad3:"Numpad 3", numpad4:"Numpad 4", numpad5:"Numpad 5", numpad6:"Numpad 6", numpad7:"Numpad 7", numpad8:"Numpad 8", numpad9:"Numpad 9", multiply:"Násobenie", add:"S�?ítanie", subtract:"Od�?ítanie", decimalPoint:"Desatinná �?iarka",
                divide:"Delenie", f1:"F1", f2:"F2", f3:"F3", f4:"F4", f5:"F5", f6:"F6", f7:"F7", f8:"F8", f9:"F9", f10:"F10", f11:"F11", f12:"F12", numLock:"Num Lock", scrollLock:"Scroll Lock", semiColon:"Bodko�?iarka", equalSign:"Rovná sa", comma:"Čiarka", dash:"Pomĺ�?ka", period:"Bodka", forwardSlash:"Lomítko", graveAccent:"Zdôrazňovanie prízvuku", openBracket:"Hranatá zátvorka otváracia", backSlash:"Backslash", closeBracket:"Hranatá zátvorka zatváracia", singleQuote:"Jednoduché úvodzovky"});